flask:
	export FLASK_APP=main.py
	export FLASK_ENV=production
	flask run -h localhost -p 3001
run-cv:
	python vision/vision.py
start:
	python -m venv ./.venv
compile:
	echo "Doesn't Exist Yet"
install:
	pip3 install -r requirements.txt
freeze:
	pip3 freeze > requirements.txt
